version: "3"

services:
  vote:
    build: ./vote
    command: python app.py
    volumes:
     - ./vote:/app
    ports:
      - "5000:80"
    networks:
      - front-network
      - back-network

  result:
    build: ./result
    command: nodemon server.js
    volumes:
      - ./result:/app
    ports:
      - "5001:80"
      - "5858:5858"
    networks:
      - front-network
      - back-network

  worker:
    build:
      context: ./worker
    depends_on:
      - "redis"
    networks:
      - back-network

  redis:
    image: redis:alpine
    container_name: redis
    ports: ["6379"]
    networks:
      - back-network

  db:
    image: postgres:9.4
    container_name: db
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-network

volumes:
  db-data:

networks:
  front-network:
    external:
        name: traefik_traefik_rp
  back-network:
