version: "3.4"
services:
    vote:
        image: example-voting-app_vote
        depends_on:
            - redis
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                max_attempts: 3
                delay: 5s
                window: 30s
            update_config:
                parallelism: 1
                delay: 20s
                order: stop-first
        networks:
            - frontend-network
            - backend-network
        labels:
            - "traefik.enable=true"
            - "traefik.frontend.rule=Host:vote.thomastran.fr"
            - "traefik.port=80"
            - "traefik.docker.network=traefik_rp"
            - "traefik.tags=memoire,python,voting-app"


    result:
        image: example-voting-app_result
        depends_on:
            - db
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                max_attempts: 3
                delay: 5s
                window: 30s
            update_config:
                parallelism: 1
                delay: 20s
                order: stop-first
        networks:
            - frontend-network
            - backend-network
        labels:
            - "traefik.enable=true"
            - "traefik.frontend.rule=Host:result.thomastran.fr"
            - "traefik.port=80"
            - "traefik.docker.network=traefik_rp"
            - "traefik.tags=memoire,nodejs,voting-app"           
  
    worker:
        image: example-voting-app_worker
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 3
                window: 120s
        networks:
            - backend-network

    redis:
        image: redis:alpine
        deploy:
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
            restart_policy:
                condition: on-failure
        networks:
            - backend-network
  
    db:
        image: postgres:9.4
        volumes:
            - db-data:/var/lib/postgresql/data
        networks:
            - backend-network
  
networks:
    frontend-network:
        external:
            name: traefik_rp
    backend-network:

volumes:
  db-data:
